## Importing the Necessary Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Loading the Dataset

In [8]:
df=pd.read_csv(r'C:\Users\admin\Downloads\virat.csv')

In [17]:
df

,Score,Out/Not Out,Against,Batting Order,Inn.,Strike Rate,Venue,Column1,H/A,Date,Result,Format,Man of the Match,Captain
0,116,Out,Australia,6,2,NaN,Adelaide Oval,Adelaide,Away,24-01-2012,Lost,Test,No,No
1,103,Out,New Zealand,5,2,NaN,M. Chinnaswamy Stadium,Bangalore,Home,31-08-2012,Won,Test,Yes,No
2,103,Out,England,5,2,NaN,Vidarbha Cricket Association Stadium,Nagpur,Home,13-12-2012,Drawn,Test,No,No
3,107,Out,Australia,5,2,NaN,M. A. Chidambaram Stadium,Chennai,Home,22-02-2013,Won,Test,No,No
4,119,Out,South Africa,4,1,NaN,Wanderers Stadium,Johannesburg,Away,18-12-2013,Drawn,Test,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,116,Out,Australia,3,1,96.67,Vidarbha Cricket Association Stadium,Nagpur,Home,05-03-2019,Won,ODI,Yes,Yes
67,123,Out,Australia,3,2,129.47,JSCA International Stadium,Ranchi,Home,08-03-2019,Lost,ODI,No,Yes
68,120,Out,West Indies,3,1,96.00,Queen's Park Oval,Port of Spain,Away,11-08-2019,Won,ODI,Yes,Yes
69,114,Not Out,West Indies,3,2,115.15,Queen's Park Oval,Port of Spain,Away,14-08-2019,Won,ODI,Yes,Yes
70,122,Not Out,Afganistan,1,1,200.00,Dubai International Cricket Stadium,Dubai,Away,08-09-2022,Won,T20I,Yes,No

In [18]:
virat=pd.DataFrame(df)

In [19]:
virat

,Score,Out/Not Out,Against,Batting Order,Inn.,Strike Rate,Venue,Column1,H/A,Date,Result,Format,Man of the Match,Captain
0,116,Out,Australia,6,2,NaN,Adelaide Oval,Adelaide,Away,24-01-2012,Lost,Test,No,No
1,103,Out,New Zealand,5,2,NaN,M. Chinnaswamy Stadium,Bangalore,Home,31-08-2012,Won,Test,Yes,No
2,103,Out,England,5,2,NaN,Vidarbha Cricket Association Stadium,Nagpur,Home,13-12-2012,Drawn,Test,No,No
3,107,Out,Australia,5,2,NaN,M. A. Chidambaram Stadium,Chennai,Home,22-02-2013,Won,Test,No,No
4,119,Out,South Africa,4,1,NaN,Wanderers Stadium,Johannesburg,Away,18-12-2013,Drawn,Test,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,116,Out,Australia,3,1,96.67,Vidarbha Cricket Association Stadium,Nagpur,Home,05-03-2019,Won,ODI,Yes,Yes
67,123,Out,Australia,3,2,129.47,JSCA International Stadium,Ranchi,Home,08-03-2019,Lost,ODI,No,Yes
68,120,Out,West Indies,3,1,96.00,Queen's Park Oval,Port of Spain,Away,11-08-2019,Won,ODI,Yes,Yes
69,114,Not Out,West Indies,3,2,115.15,Queen's Park Oval,Port of Spain,Away,14-08-2019,Won,ODI,Yes,Yes
70,122,Not Out,Afganistan,1,1,200.00,Dubai International Cricket Stadium,Dubai,Away,08-09-2022,Won,T20I,Yes,No

## Cleaning the Dataset

In [20]:
virat.isnull().sum()

Score                0
Out/Not Out          0
Against              0
Batting Order        0
Inn.                 0
Strike Rate         27
Venue                0
Column1              0
H/A                  0
Date                 0
Result               0
Format               0
Man of the Match     0
Captain              0
dtype: int64

In [27]:
virat["Strike Rate"]=virat["Strike Rate"].fillna(virat["Strike Rate"].mean())

In [28]:
virat

,Score,Out/Not Out,Against,Batting Order,Inn.,Strike Rate,Venue,Column1,H/A,Date,Result,Format,Man of the Match,Captain
0,116,Out,Australia,6,2,114.019545,Adelaide Oval,Adelaide,Away,24-01-2012,Lost,Test,No,No
1,103,Out,New Zealand,5,2,114.019545,M. Chinnaswamy Stadium,Bangalore,Home,31-08-2012,Won,Test,Yes,No
2,103,Out,England,5,2,114.019545,Vidarbha Cricket Association Stadium,Nagpur,Home,13-12-2012,Drawn,Test,No,No
3,107,Out,Australia,5,2,114.019545,M. A. Chidambaram Stadium,Chennai,Home,22-02-2013,Won,Test,No,No
4,119,Out,South Africa,4,1,114.019545,Wanderers Stadium,Johannesburg,Away,18-12-2013,Drawn,Test,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,116,Out,Australia,3,1,96.670000,Vidarbha Cricket Association Stadium,Nagpur,Home,05-03-2019,Won,ODI,Yes,Yes
67,123,Out,Australia,3,2,129.470000,JSCA International Stadium,Ranchi,Home,08-03-2019,Lost,ODI,No,Yes
68,120,Out,West Indies,3,1,96.000000,Queen's Park Oval,Port of Spain,Away,11-08-2019,Won,ODI,Yes,Yes
69,114,Not Out,West Indies,3,2,115.150000,Queen's Park Oval,Port of Spain,Away,14-08-2019,Won,ODI,Yes,Yes
70,122,Not Out,Afganistan,1,1,200.000000,Dubai International Cricket Stadium,Dubai,Away,08-09-2022,Won,T20I,Yes,No

In [29]:
virat.isnull().sum()

Score               0
Out/Not Out         0
Against             0
Batting Order       0
Inn.                0
Strike Rate         0
Venue               0
Column1             0
H/A                 0
Date                0
Result              0
Format              0
Man of the Match    0
Captain             0
dtype: int64

In [30]:
virat.rename(columns={"Column1":"City"},inplace=True)

In [31]:
virat

,Score,Out/Not Out,Against,Batting Order,Inn.,Strike Rate,Venue,City,H/A,Date,Result,Format,Man of the Match,Captain
0,116,Out,Australia,6,2,114.019545,Adelaide Oval,Adelaide,Away,24-01-2012,Lost,Test,No,No
1,103,Out,New Zealand,5,2,114.019545,M. Chinnaswamy Stadium,Bangalore,Home,31-08-2012,Won,Test,Yes,No
2,103,Out,England,5,2,114.019545,Vidarbha Cricket Association Stadium,Nagpur,Home,13-12-2012,Drawn,Test,No,No
3,107,Out,Australia,5,2,114.019545,M. A. Chidambaram Stadium,Chennai,Home,22-02-2013,Won,Test,No,No
4,119,Out,South Africa,4,1,114.019545,Wanderers Stadium,Johannesburg,Away,18-12-2013,Drawn,Test,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,116,Out,Australia,3,1,96.670000,Vidarbha Cricket Association Stadium,Nagpur,Home,05-03-2019,Won,ODI,Yes,Yes
67,123,Out,Australia,3,2,129.470000,JSCA International Stadium,Ranchi,Home,08-03-2019,Lost,ODI,No,Yes
68,120,Out,West Indies,3,1,96.000000,Queen's Park Oval,Port of Spain,Away,11-08-2019,Won,ODI,Yes,Yes
69,114,Not Out,West Indies,3,2,115.150000,Queen's Park Oval,Port of Spain,Away,14-08-2019,Won,ODI,Yes,Yes
70,122,Not Out,Afganistan,1,1,200.000000,Dubai International Cricket Stadium,Dubai,Away,08-09-2022,Won,T20I,Yes,No

In [32]:
virat.drop(columns="Out/Not Out",inplace=True)

In [33]:
virat

,Score,Against,Batting Order,Inn.,Strike Rate,Venue,City,H/A,Date,Result,Format,Man of the Match,Captain
0,116,Australia,6,2,114.019545,Adelaide Oval,Adelaide,Away,24-01-2012,Lost,Test,No,No
1,103,New Zealand,5,2,114.019545,M. Chinnaswamy Stadium,Bangalore,Home,31-08-2012,Won,Test,Yes,No
2,103,England,5,2,114.019545,Vidarbha Cricket Association Stadium,Nagpur,Home,13-12-2012,Drawn,Test,No,No
3,107,Australia,5,2,114.019545,M. A. Chidambaram Stadium,Chennai,Home,22-02-2013,Won,Test,No,No
4,119,South Africa,4,1,114.019545,Wanderers Stadium,Johannesburg,Away,18-12-2013,Drawn,Test,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,116,Australia,3,1,96.670000,Vidarbha Cricket Association Stadium,Nagpur,Home,05-03-2019,Won,ODI,Yes,Yes
67,123,Australia,3,2,129.470000,JSCA International Stadium,Ranchi,Home,08-03-2019,Lost,ODI,No,Yes
68,120,West Indies,3,1,96.000000,Queen's Park Oval,Port of Spain,Away,11-08-2019,Won,ODI,Yes,Yes
69,114,West Indies,3,2,115.150000,Queen's Park Oval,Port of Spain,Away,14-08-2019,Won,ODI,Yes,Yes
70,122,Afganistan,1,1,200.000000,Dubai International Cricket Stadium,Dubai,Away,08-09-2022,Won,T20I,Yes,No

In [37]:
virat.drop(["Captain"],axis=1,inplace=True)

In [38]:
virat

,Score,Against,Batting Order,Inn.,Strike Rate,Venue,City,H/A,Date,Result,Format,Man of the Match
0,116,Australia,6,2,114.019545,Adelaide Oval,Adelaide,Away,24-01-2012,Lost,Test,No
1,103,New Zealand,5,2,114.019545,M. Chinnaswamy Stadium,Bangalore,Home,31-08-2012,Won,Test,Yes
2,103,England,5,2,114.019545,Vidarbha Cricket Association Stadium,Nagpur,Home,13-12-2012,Drawn,Test,No
3,107,Australia,5,2,114.019545,M. A. Chidambaram Stadium,Chennai,Home,22-02-2013,Won,Test,No
4,119,South Africa,4,1,114.019545,Wanderers Stadium,Johannesburg,Away,18-12-2013,Drawn,Test,No
...,...,...,...,...,...,...,...,...,...,...,...,...
66,116,Australia,3,1,96.670000,Vidarbha Cricket Association Stadium,Nagpur,Home,05-03-2019,Won,ODI,Yes
67,123,Australia,3,2,129.470000,JSCA International Stadium,Ranchi,Home,08-03-2019,Lost,ODI,No
68,120,West Indies,3,1,96.000000,Queen's Park Oval,Port of Spain,Away,11-08-2019,Won,ODI,Yes
69,114,West Indies,3,2,115.150000,Queen's Park Oval,Port of Spain,Away,14-08-2019,Won,ODI,Yes
70,122,Afganistan,1,1,200.000000,Dubai International Cricket Stadium,Dubai,Away,08-09-2022,Won,T20I,Yes

In [39]:
virat.rename(columns={"Inn.":"Innings"},inplace=True)

In [40]:
virat

,Score,Against,Batting Order,Innings,Strike Rate,Venue,City,H/A,Date,Result,Format,Man of the Match
0,116,Australia,6,2,114.019545,Adelaide Oval,Adelaide,Away,24-01-2012,Lost,Test,No
1,103,New Zealand,5,2,114.019545,M. Chinnaswamy Stadium,Bangalore,Home,31-08-2012,Won,Test,Yes
2,103,England,5,2,114.019545,Vidarbha Cricket Association Stadium,Nagpur,Home,13-12-2012,Drawn,Test,No
3,107,Australia,5,2,114.019545,M. A. Chidambaram Stadium,Chennai,Home,22-02-2013,Won,Test,No
4,119,South Africa,4,1,114.019545,Wanderers Stadium,Johannesburg,Away,18-12-2013,Drawn,Test,No
...,...,...,...,...,...,...,...,...,...,...,...,...
66,116,Australia,3,1,96.670000,Vidarbha Cricket Association Stadium,Nagpur,Home,05-03-2019,Won,ODI,Yes
67,123,Australia,3,2,129.470000,JSCA International Stadium,Ranchi,Home,08-03-2019,Lost,ODI,No
68,120,West Indies,3,1,96.000000,Queen's Park Oval,Port of Spain,Away,11-08-2019,Won,ODI,Yes
69,114,West Indies,3,2,115.150000,Queen's Park Oval,Port of Spain,Away,14-08-2019,Won,ODI,Yes
70,122,Afganistan,1,1,200.000000,Dubai International Cricket Stadium,Dubai,Away,08-09-2022,Won,T20I,Yes